version: '3.7'
services:
  nginx:
    image: library/nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      - blog

  mysql:
    image: library/mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: blogDB
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    ports:
      - 3309:3306
    volumes:
      - ../mysql:/var/lib/mysql
    networks:
      - blog

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - 9000:80
    volumes:
      - ./:/var/www/html
    networks:
      - blog

networks:
  blog:
    driver: bridge

